version: '3'

services:
  strapi:
    build: .
    container_name: strapi-recette
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
